/**
 * Menu configuration - Generated from Menu_LGC.csv
 * Contains all categories and their sub-menus
 */

export const menuConfig = [
  {
    category: "APPELS D'OFFRES",
    icon: "FileText",
    path: "/appels-offres",
    permission: "appels_offres:view",
    subMenus: [
      { label: "Nouveau", path: "/appels-offres/nouveau" },
      { label: "Consulter", path: "/appels-offres/consulter" },
      { label: "Accord Participation", path: "/appels-offres/accord-participation" },
      { label: "Préparer", path: "/appels-offres/preparer" },
      { label: "En attente résultat", path: "/appels-offres/attente-resultat" },
      { label: "Attribué", path: "/appels-offres/attribue" },
      { label: "Marché", path: "/appels-offres/marche" },
      { label: "Situation caution", path: "/appels-offres/situation-caution" },
      { label: "M.à.j Caution", path: "/appels-offres/maj-caution" },
      { label: "Caution à récupérer", path: "/appels-offres/caution-recuperer" },
      { label: "Résultat AO", path: "/appels-offres/resultat" },
      { label: "Consultation Globale", path: "/appels-offres/consultation-globale" },
      { label: "Statistique AO", path: "/appels-offres/statistique" },
      { label: "Qualification AO", path: "/appels-offres/qualification" },
    ],
  },
  {
    category: "MARCHÉS",
    icon: "ShoppingCart",
    path: "/marches",
    permission: "marches:view",
    subMenus: [
      { label: "Nouveau", path: "/marches/nouveau" },
      { label: "Consulter Marché", path: "/marches/consulter" },
      { label: "Caution définitive", path: "/marches/caution-definitive" },
    ],
  },
  {
    category: "DEVIS",
    icon: "FileSignature",
    path: "/devis",
    permission: "devis:view",
    subMenus: [
      { label: "Nouveau", path: "/devis/nouveau" },
      { label: "Consulter", path: "/devis/consulter" },
      { label: "Situation BC", path: "/devis/situation-bc" },
      { label: "Référentiel des prix", path: "/devis/referentiel-prix" },
      { label: "Détails devis", path: "/devis/details" },
      { label: "Paramétrage modèle", path: "/devis/parametrage-modele" },
    ],
  },
  {
    category: "PROJETS",
    icon: "FolderKanban",
    path: "/projets",
    permission: "projets:view",
    subMenus: [
      { label: "Nouveau", path: "/projets/nouveau" },
      { label: "Modifier", path: "/projets/modifier" },
      { label: "Consulter", path: "/projets/consulter" },
      { label: "Supprimer", path: "/projets/supprimer" },
      { label: "Sous projet", path: "/projets/sous-projet" },
      { label: "Statistique", path: "/projets/statistique" },
      { label: "Situation projets", path: "/projets/situation" },
      { label: "Géolocalisation", path: "/projets/geolocalisation" },
      { label: "Changement des affectations", path: "/projets/affectations" },
    ],
  },
  {
    category: "RÉCEPTIONS",
    icon: "ClipboardCheck",
    path: "/receptions",
    permission: "receptions:view",
    subMenus: [
      { label: "Nouveau", path: "/receptions/nouveau" },
      { label: "Nouvelle Réception (Prise en charge traction +compression)", path: "/receptions/prise-charge" },
      { label: "Pré Réception", path: "/receptions/pre-reception" },
      { label: "Nouvelle réception étude", path: "/receptions/reception-etude" },
      { label: "Supprimer réception", path: "/receptions/supprimer" },
      { label: "Essai autre matériaux", path: "/receptions/essai-autres" },
      { label: "Essai Béton", path: "/receptions/essai-beton" },
      { label: "Gestion cylindre", path: "/receptions/gestion-cylindre" },
      { label: "Modifier réception", path: "/receptions/modifier" },
      { label: "Suivi autres matériaux", path: "/receptions/suivi-autres" },
      { label: "Essai béton (LABO)", path: "/receptions/essai-beton-labo" },
      { label: "Consultation essai (Interne/Externe)", path: "/receptions/consultation-essai" },
      { label: "Traitement des essai Labo", path: "/receptions/traitement-essai" },
      { label: "Initialisation", path: "/receptions/initialisation" },
      { label: "Planning", path: "/receptions/planning" },
    ],
  },
  {
    category: "RAPPORTS",
    icon: "FileBarChart",
    path: "/rapports",
    permission: "rapports:view",
    subMenus: [
      { label: "À faire : Autres Matériaux", path: "/rapports/a-faire-autres" },
      { label: "À faire : Béton", path: "/rapports/a-faire-beton" },
      { label: "À faire Global", path: "/rapports/a-faire-global" },
      { label: "Modifier", path: "/rapports/modifier" },
      { label: "Consulter Rapport/Prix", path: "/rapports/consulter" },
      { label: "Rapport de synthèse", path: "/rapports/synthese" },
      { label: "État livraison rapports", path: "/rapports/etat-livraison" },
      { label: "Édition Rapport", path: "/rapports/edition" },
      { label: "Rapport d'étude", path: "/rapports/etude" },
    ],
  },
  {
    category: "FACTURATION",
    icon: "Receipt",
    path: "/facturation",
    permission: "facturation:view",
    subMenus: [
      { label: "Nouvelle facture", path: "/facturation/nouvelle" },
      { label: "Rapport à facturer", path: "/facturation/rapport-a-facturer" },
      { label: "Rapport à facturer par projet", path: "/facturation/rapport-par-projet" },
      { label: "Création", path: "/facturation/creation" },
      { label: "Consultation/Edition Factures", path: "/facturation/consultation" },
      { label: "Attachement", path: "/facturation/attachement" },
      { label: "En livraison Factures", path: "/facturation/livraison" },
      { label: "Autres factures", path: "/facturation/autres" },
      { label: "Factures/BL annulées", path: "/facturation/annulees" },
      { label: "Pré-facture (BL)", path: "/facturation/pre-facture" },
      { label: "Facture avoir", path: "/facturation/avoir" },
    ],
  },
  {
    category: "RÈGLEMENTS CLIENTS",
    icon: "CreditCard",
    path: "/reglements-clients",
    permission: "reglements_clients:view",
    subMenus: [
      { label: "Nouveau", path: "/reglements-clients/nouveau" },
      { label: "Avance", path: "/reglements-clients/avance" },
      { label: "Consulter Règlements", path: "/reglements-clients/consulter" },
      { label: "En instance", path: "/reglements-clients/instance" },
      { label: "Suivi paiement factures", path: "/reglements-clients/suivi-paiement" },
      { label: "Relevé Client", path: "/reglements-clients/releve-client" },
      { label: "Relevé par projet", path: "/reglements-clients/releve-projet" },
      { label: "Situation globale/projet", path: "/reglements-clients/situation-projet" },
      { label: "Situation globale financière", path: "/reglements-clients/situation-financiere" },
      { label: "Règlements annulés", path: "/reglements-clients/annules" },
      { label: "État Impayé", path: "/reglements-clients/impaye" },
    ],
  },
  {
    category: "BORDEREAUX",
    icon: "FileSpreadsheet",
    path: "/bordereaux",
    permission: "bordereaux:view",
    subMenus: [
      { label: "Bordereau à faire/Rapports", path: "/bordereaux/a-faire" },
      { label: "Modification/Edition", path: "/bordereaux/modification" },
      { label: "Livraison", path: "/bordereaux/livraison" },
    ],
  },
  {
    category: "ACHATS",
    icon: "ShoppingBag",
    path: "/achats",
    permission: "achats:view",
    subMenus: [
      { label: "Paramétrage", path: "/achats/parametrage" },
      { label: "Fournisseur", path: "/achats/fournisseur" },
      { label: "Validation Dossier Achat", path: "/achats/validation" },
      { label: "Dossier Achat", path: "/achats/dossier" },
      { label: "Dépense fournisseurs", path: "/achats/depense" },
      { label: "Règlements fournisseurs", path: "/achats/reglements" },
      { label: "Budget et Objectif", path: "/achats/budget" },
    ],
  },
  {
    category: "PERSONNEL",
    icon: "Users",
    path: "/personnel",
    permission: "personnel:view",
    subMenus: [
      { label: "Dossier Salarié", path: "/personnel/dossier-salarie" },
      { label: "Dossier Administratif", path: "/personnel/dossier-admin" },
      { label: "Expérience", path: "/personnel/experience" },
      { label: "Droit congé", path: "/personnel/droit-conge" },
      { label: "Congé", path: "/personnel/conge" },
      { label: "Paie", path: "/personnel/paie" },
    ],
  },
  {
    category: "TRÉSORERIE",
    icon: "Wallet",
    path: "/tresorerie",
    permission: "tresorerie:view",
    subMenus: [
      { label: "Situation", path: "/tresorerie/situation" },
      { label: "Banque", path: "/tresorerie/banque" },
      { label: "Dépenses", path: "/tresorerie/depenses" },
      { label: "Caisse siège", path: "/tresorerie/caisse-siege" },
      { label: "Caisse agence", path: "/tresorerie/caisse-agence" },
      { label: "Caisse employé", path: "/tresorerie/caisse-employe" },
    ],
  },
  {
    category: "LOGISTIQUE",
    icon: "Truck",
    path: "/logistique",
    permission: "logistique:view",
    subMenus: [
      { label: "Véhicules", path: "/logistique/vehicules" },
      { label: "Foyers", path: "/logistique/foyers" },
      { label: "Matériel", path: "/logistique/materiel" },
      { label: "Autre Matériel", path: "/logistique/autre-materiel" },
      { label: "Crédit & loyer", path: "/logistique/credit-loyer" },
    ],
  },
  {
    category: "CLIENTS",
    icon: "UserCheck",
    path: "/clients",
    permission: "clients:view",
    subMenus: [
      { label: "Mise à jours", path: "/clients/mise-a-jour" },
      { label: "Situation Clients", path: "/clients/situation" },
      { label: "Situation Client/Projet", path: "/clients/situation-projet" },
      { label: "Liste rapports facturés", path: "/clients/rapports-factures" },
      { label: "Situation Client/Facture", path: "/clients/situation-facture" },
    ],
  },
  {
    category: "MESSAGERIE",
    icon: "Mail",
    path: "/messagerie",
    permission: "messagerie:view",
    subMenus: [
      { label: "Envoi courrier", path: "/messagerie/envoi" },
      { label: "Réception courrier", path: "/messagerie/reception" },
      { label: "Message interne", path: "/messagerie/interne" },
      { label: "Remarque application", path: "/messagerie/remarque" },
      { label: "Demande annulation", path: "/messagerie/demande-annulation" },
      { label: "Demande ajout client", path: "/messagerie/demande-ajout-client" },
    ],
  },
  {
    category: "G.E.D",
    icon: "FolderOpen",
    path: "/ged",
    permission: "ged:view",
    subMenus: [
      { label: "Télécharger document", path: "/ged/telecharger" },
      { label: "Scanner document", path: "/ged/scanner" },
      { label: "Rechercher documents", path: "/ged/rechercher" },
      { label: "Mise à jour référencement", path: "/ged/maj-referencement" },
      { label: "Supprimer document", path: "/ged/supprimer" },
      { label: "Historique mouvement", path: "/ged/historique" },
    ],
  },
  {
    category: "PARAMÉTRAGE",
    icon: "Settings",
    path: "/parametrage",
    permission: "parametrage:view",
    subMenus: [
      { label: "Global", path: "/parametrage/global" },
      { label: "Projets", path: "/parametrage/projets" },
      { label: "Métier", path: "/parametrage/metier" },
      { label: "Graphe", path: "/parametrage/graphe" },
      { label: "Société", path: "/parametrage/societe" },
      { label: "Utilisateur", path: "/parametrage/utilisateur" },
      { label: "Connexion", path: "/parametrage/connexion" },
      { label: "Initiation Table", path: "/parametrage/initiation-table" },
      { label: "Paramétrage Objectifs", path: "/parametrage/objectifs" },
      { label: "G.E.D", path: "/parametrage/ged" },
    ],
  },
  {
    category: "DROITS",
    icon: "Shield",
    path: "/droits",
    permission: "droits:view",
    subMenus: [
      { label: "Menu Administrateur", path: "/droits/menu-admin" },
      { label: "Menu Fonctionnelle", path: "/droits/menu-fonctionnelle" },
      { label: "Affectation charges", path: "/droits/affectation-charges" },
      { label: "Liste des Tâches", path: "/droits/taches" },
      { label: "Client", path: "/droits/client" },
      { label: "Régions et Villes", path: "/droits/regions-villes" },
    ],
  },
];

// Keep Dashboard and HR for demo purposes
export const defaultMenuItems = [
  {
    category: "DASHBOARD",
    icon: "LayoutDashboard",
    path: "/dashboard",
    permission: "dashboard:view",
    subMenus: [],
  },
  {
    category: "HR",
    icon: "Users",
    path: "/hr",
    permission: "hr:view",
    subMenus: [
      { label: "Employees", path: "/hr/employees" },
    ],
  },
];
